# config/exp1.yaml
N: 15  # Lookback window (seconds)
X: 5   # Prediction window (seconds)

# Defining train/test split percentages for capture windows
# Format: [percentage_window_1, percentage_window_2]
train_test_split:
  A->B:
    train: [80, 0]
    test: [20, 0]
  B->A:
    train: [80, 0]
    test: [20, 0]
  B->C:
    train: [0, 0]
    test: [0, 0]
  C->B:
    train: [0, 0]
    test: [0, 0]
  A->C:
    train: [80, 0]
    test: [20, 0]
  C->A:
    train: [80, 0]
    test: [20, 0]
